name: KennyODonnell
favicon: null
layout_spectrum: 0.24725
typography_spectrum: 1
title: "The Online Resumé of Kenny O'Donnell"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#060606'
    - '#baa57a'
    - '#3d2b27'
    - '#827773'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.14884065627120435
  rhythmicContrast: 0.5598966181278229
purpose: []
