name: KennyODonnell
favicon: null
layout_spectrum: 0.9833645452745259
typography_spectrum: 0.08650644076988101
title: "The Online Resumé of Kenny O'Donnell"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#1a6f2e'
    - '#a5aca5'
    - '#e8e5de'
    - '#881a09'
  brandStrength: 0.9029595197644085
  lightness: 0.3125
  saturation: 0.14884065627120435
  rhythmicContrast: 0.5598966181278229
purpose: []
